=== teosoncco/python-print-form/pyForm/PyForm.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
 
    <xs:complexType name="VariableSetValue">
        <xs:attribute name="name" use="required" type="xs:string"/>
        <xs:attribute name="value" use="required" type="xs:string"/>
        <xs:attribute name="format" use="optional" type="xs:string"/>
    </xs:complexType>
 
     <xs:complexType name="Color">
        <xs:attribute name="red" use="optional" type="xs:integer"/>
        <xs:attribute name="green" use="optional" type="xs:integer"/>
        <xs:attribute name="blue" use="optional" type="xs:integer"/>
         <xs:attribute name="standard" >
             <xs:simpleType>
                 <xs:restriction base="xs:string">
                     <xs:enumeration value="white"/>
                     <xs:enumeration value="black"/>
                     <xs:enumeration value="red"/>
                     <xs:enumeration value="green"/>
                     <xs:enumeration value="blue"/>
                 </xs:restriction>
             </xs:simpleType>
         </xs:attribute >
    </xs:complexType>

    <xs:complexType name="Element" abstract="true" mixed="true">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="foregroundColor" type="Color" minOccurs="0"/>
            <xs:element name="backgroundColor" type="Color" minOccurs="0"/>
        </xs:choice>
        <xs:attribute name="name" type="xs:string" use="optional"/>
        <xs:attribute name="top" type="xs:float" use="optional" default="0"/>
        <xs:attribute name="left" type="xs:float" use="optional" default="0"/>
        <xs:attribute name="enabled" type="xs:string" use="optional" default="True"/>
    </xs:complexType>          
        
    <xs:simpleType name="Align">
        <xs:restriction base="xs:string">
            <xs:enumeration value="left"/>
            <xs:enumeration value="right"/>
            <xs:enumeration value="centre"/>
            <xs:enumeration value="justified"><!-- solo en multicells--> </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Font">
        <xs:attribute name="family" >
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="courier"/>
                    <xs:enumeration value="helvetica"/>
                    <xs:enumeration value="arial"/>
                    <xs:enumeration value="times"/>
                    <xs:enumeration value="symbol"/>
                    <xs:enumeration value="zapfdingbats"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute >                        
        <xs:attribute name="bold" type="xs:boolean" use="optional" default="false"/>
        <xs:attribute name="italic" type="xs:boolean" use="optional" default="false"/>
        <xs:attribute name="underline" type="xs:boolean" use="optional" default="false"/>
        <xs:attribute name="compressed" type="xs:boolean" use="optional" default="false"/>        
        <xs:attribute name="size" type="xs:string" use="optional" default="12"/>
    </xs:complexType>

    <xs:simpleType name="LineWidth">
        <xs:restriction base="xs:float">
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="Border">
        <xs:attribute name="left" type="xs:boolean" use="optional" default="false"/>
        <xs:attribute name="right" type="xs:boolean" use="optional" default="false"/>
        <xs:attribute name="top" type="xs:boolean" use="optional" default="false"/>
        <xs:attribute name="bottom" type="xs:boolean" use="optional" default="false"/>
        <xs:attribute name="lineWidth" type="LineWidth" use="optional" />
    </xs:complexType>

    <xs:complexType name="Text" mixed="true">
        <xs:complexContent>
            <xs:extension base="Element">
                <xs:sequence>
                    <xs:element name="font" type="Font" minOccurs="0" maxOccurs="1"/>
                </xs:sequence>
                <xs:attribute name="angle" type="xs:float" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Barcode" mixed="true">
        <xs:complexContent>
            <xs:extension base="Element">
                <xs:attribute name="barcode">
                   <xs:simpleType>
                       <xs:restriction base="xs:string">
                           <xs:enumeration value="code39"/>
                           <xs:enumeration value="interleaved25"/>
                           <xs:enumeration value="ean13"/>
                           <xs:enumeration value="upc_a"/>
                           <xs:enumeration value="codabar"/>
                       </xs:restriction>
                   </xs:simpleType>
                </xs:attribute >
                <xs:attribute name="width" type="xs:float" use="optional"/>
                <xs:attribute name="height" type="xs:float" use="optional"/>            
                <xs:attribute name="angle" type="xs:float" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Cell" mixed="true">
        <xs:complexContent>
            <xs:extension base="Element">
                <xs:sequence>
                    <xs:element name="font" type="Font" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="border" type="Border" minOccurs="0" maxOccurs="1"/>
                </xs:sequence>
                <xs:attribute name="align" type="Align" use="optional" default="left"/>
                <xs:attribute name="fill" type="xs:boolean" use="optional" default="false"/>
                <xs:attribute name="width" type="xs:float" use="required"/>
                <xs:attribute name="height" type="xs:float" use="optional"/>
                <xs:attribute name="multiline" type="xs:boolean" use="optional" default="false"/>
                <xs:attribute name="maxlines" type="xs:int" use="optional" default="0"/><!-- solo para multiline=true -->
                <xs:attribute name="angle" type="xs:float" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="Line">
        <xs:complexContent>
            <xs:extension base="Element">
                <xs:attribute name="height" type="xs:float" use="optional"/>
                <xs:attribute name="width" type="xs:float" use="optional"/>
                <xs:attribute name="lineWidth" type="LineWidth" use="optional" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Rect">
        <xs:complexContent>
            <xs:extension base="Element">
                <xs:sequence>
                </xs:sequence>
                <xs:attribute name="height" type="xs:float" use="optional"/>
                <xs:attribute name="width" type="xs:float" use="optional"/>
                <xs:attribute name="lineWidth" type="LineWidth" use="optional" />
                <xs:attribute name="fill" type="xs:boolean" use="optional" default="false"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Image">
        <xs:complexContent>
            <xs:extension base="Element">
                <xs:sequence>
                </xs:sequence>
                <xs:attribute name="filename" type="xs:string" use="required"/>
                <xs:attribute name="height" type="xs:float" use="optional"/>
                <xs:attribute name="width" type="xs:float" use="optional"/>
                <xs:attribute name="type" use="optional">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="jpg"/>
                            <xs:enumeration value="jpeg"/>
                            <xs:enumeration value="png"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute >
                <xs:attribute name="angle" type="xs:float" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

     <xs:complexType name="Container" mixed="true">
        <xs:complexContent>
            <xs:extension base="Element">
                <xs:sequence minOccurs="0" maxOccurs="unbounded" >
                    <xs:element name="elements" maxOccurs="1" minOccurs="0">
                        <xs:complexType>
                            <xs:choice minOccurs="0" maxOccurs="unbounded">
                                <xs:element name="text" type="Text"/>
                                <xs:element name="line" type="Line"/>
                                <xs:element name="rect" type="Rect"/>
                                <xs:element name="cell" type="Cell"/>
                                <xs:element name="image" type="Image"/>
                                <xs:element name="container" type="Container"/>
                                <xs:element name="barcode" type="Barcode"/>
                            </xs:choice>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="variables" minOccurs="0">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="variable" type="VariableSetValue" minOccurs="1" maxOccurs="unbounded"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="defaultFont" type="Font" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="defaultLineWidth" type="LineWidth" minOccurs="0" maxOccurs="1"/>                    
                </xs:sequence>
                <xs:attribute name="width" type="xs:float" use="optional"/>
                <xs:attribute name="height" type="xs:float" use="optional"/>
                <xs:attribute name="rows" type="xs:float" use="optional"/>
                <xs:attribute name="cols" type="xs:float" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Margins">
        <xs:attribute name="top" type="xs:float" use="required"/>
        <xs:attribute name="left" type="xs:float" use="required"/>
        <xs:attribute name="right" type="xs:float" use="optional"/>
    </xs:complexType>
    
    <xs:element name="form" type="Form"/>
    <xs:complexType name="Form">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="margins" type="Margins" minOccurs="0" maxOccurs="1"/>            
            <xs:element name="variables" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="variable" type="VariableSetValue" minOccurs="1" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            
            <xs:element name="title" maxOccurs="1" minOccurs="0" type="xs:string"/>

            <xs:element name="implementation" minOccurs="1" maxOccurs="1">
                <xs:complexType >
                    <xs:attribute name="module" use="required" type="xs:string"/>
                    <xs:attribute name="function" use="required" type="xs:string"/>
                </xs:complexType>
           </xs:element>           
        
            <xs:element name="header" type="Container" minOccurs="0" maxOccurs="1"/>
            <xs:element name="body" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:complexContent>                        
                        <xs:extension base="Container">
                            <xs:attribute name="copies" type="xs:integer" use="optional"/>                            
                        </xs:extension>
                    </xs:complexContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="footer" type="Container" minOccurs="0" maxOccurs="1"/>
            
        </xs:sequence>
        <xs:attribute name="format" >
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="A4"/>
                    <xs:enumeration value="letter"/>
                    <xs:enumeration value="legal"/>
                    <xs:enumeration value="A3"/>
                    <xs:enumeration value="A5"/>
                    <xs:enumeration value="custom"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute >                        
        <xs:attribute  name="orientation" default="portrait">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="portrait"/>
                    <xs:enumeration value="landscape"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute >
        <xs:attribute  name="unit" default="mm">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="mm"/>
                    <xs:enumeration value="cm"/>
                    <xs:enumeration value="pt"/>
                    <xs:enumeration value="in"/>
                    <xs:enumeration value="chars"/> <!-- solo para texto plano -->                   
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="author" type="xs:string" use="optional"/>
        <xs:attribute name="subject" type="xs:string" use="optional"/>
        <xs:attribute name="creator" type="xs:string" use="optional" default="Lambda PyForm"/>        
        <xs:attribute name="engine" default="fpdf">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="fpdf"/>
                    <xs:enumeration value="text"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute >
        <xs:attribute name="collateCopies" type="xs:boolean" use="optional" default="false"/>
    </xs:complexType>

</xs:schema>

=== teosoncco/python-print-form/samples/facturaLaser.xml
<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="file:/home/guido/src/fierro/pyForm/PyForm.xsd">

    <margins top="10" left="17"/>
    <variables>
        <variable name="debug" value="False"/>
        <variable name="itemsPP" value="27"/>
    </variables>

    <title>"Factura E SigloXXI"</title>

    <implementation module="colofon.client.model.printableModel2" function="printSaleBill"/>

    <body name="hoja1" copies="2">
        <backgroundColor standard="white"/>
        <foregroundColor standard="black"/>
        <defaultFont family="arial" size="8"/>
        <defaultLineWidth>0.2</defaultLineWidth>

        <elements>
            <container name="ficha" top="0" left="0" width="185" height="280" rows="1" cols="1" enabled="True">
                <elements>
                    <cell top="7" left="135" width="50" height="10" align="left">doc.description</cell>
                    <cell top="13" left="140" width="30" height="10" align="left">
                        <font family="times" bold="true" size="12"/>
                        doc.date
                    </cell>

                    <cell top="40" left="21" width="100" height="10" align="left">doc.client.legalName</cell>
                    <cell top="46" left="21" width="100" height="10" align="left">doc.client.address.getAddress(['%(address)s'])</cell>
                    <cell top="52" left="21" width="100" height="10" align="left">doc.client.address.getAddress(['%(localidad)s'])</cell>
                    <cell top="58" left="21" width="100" height="10" align="left">doc.client.address.getAddress( [ '%(phone)s'])</cell>
                    <cell top="68" left="21" width="100" height="10" align="left">doc.client.clientCode</cell>

                    <cell top="40" left="153" width="35" height="10" align="left">doc.client.cuit</cell>
                    <cell top="46" left="153" width="35" height="10" align="left">doc.client.typeIva</cell>
                    <cell top="53" left="153" width="35" height="10" align="left">doc.dueDate</cell>
                    <cell top="61" left="153" width="35" height="10" align="left">doc.payments</cell>
                    <cell top="68" left="153" width="35" height="10" align="left">doc.headerRemits</cell>
                    <cell top="75" left="153" width="35" height="10" align="left">doc.legalQuotation</cell>

                    <container name="ficha" top="92" left="0" width="185" height="5" rows="27" cols="1" enabled="(row  + (pgno * itemsPP) ) &lt; len (doc.itemsAndConcepts)">
                        <elements>
                            <cell top="0" left="0" width="10" height="5" align="left">doc.itemsAndConcepts[row].quantity</cell>
                            <cell top="0" left="15" width="40" height="5" align="left"><font size="8"/>doc.itemsAndConcepts[row].isbn</cell>
                            <cell top="0" left="50" width="80" height="5" align="left">doc.itemsAndConcepts[row].description</cell>
                            <cell top="0" left="130" width="20" height="5" align="right">doc.itemsAndConcepts[row].priceDto</cell>
                            <cell top="0" left="158" width="22" height="5" align="right">doc.itemsAndConcepts[row].total</cell>
                        </elements>
                    </container>

                    <cell top="240" left="5" width="26" height="10" align="left">doc.itemsQuantity</cell>
                    <cell top="240" left="55" width="33" height="10" align="left">doc.productQuantity</cell>
                    <cell top="240" left="114" width="27" height="10" align="left">doc.weight</cell>
                    <cell top="220" left="150" width="30" height="10" align="right">doc.subTotal</cell>
                    <cell top="237" left="150" width="30" height="10" align="right">
                        <font family="times" bold="true" size="14"/>
                        doc.total
                    </cell>
                    <cell top="220" left="5" width="130" height="5" align="left" multiline="true" maxlines="3">doc.footerNotes()</cell>
                    <cell top="248" left="15" width="130" height="5" align="left">doc.total.getSonPesos()</cell>
                    <cell top="271" left="143" width="50" height="10" align="left"><font family="arial" bold="true" size="8"/>doc.transactionUser</cell>

                </elements>
            </container>
        </elements>
    </body>
</form>

=== teosoncco/python-print-form/pyForm/PyFormMultilineTest.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<form xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../../pyForm/PyForm.xsd" format="A4"
  orientation="portrait" unit="mm" author="Noemi" subject="cupones-luma">
  <margins top="15" left="15"/>
  <variables>
    <variable name="debug" value="False"/>
  </variables>

  <title>"Ejemplo multicell (lineas multiples)"</title>


  <body name="hoja1" copies="1">
    <backgroundColor standard="white"/>
    <foregroundColor standard="black"/>
    <defaultFont family="arial" size="12"/>
    <defaultLineWidth>0.2</defaultLineWidth>
    <elements>
      <container name="quota" top="0" left="0" width="200" height="300" rows="1" cols="1"
        enabled="True">

        <elements>
          <cell name="texto3" width="90" top="55" height="5" multiline="true" align="justified" >'esto no se imprime porque no se definio maxlines'</cell>
          <cell name="texto" width="90" top="105" height="5" multiline="true" align="justified" maxlines="1"> 'Ante la falta del pago de las cuotas atrasadas de su crédito, nos vemos en la obligación de hacerle llegar la presente ya que la gestión de nuestro cobrador se ha visto frustrada porque no consiguió que usted cancelara las cuotas en mora. Intimamos la cancelación de dichas cuotas atrasadas que suman $20.000.- en forma inmediata para evitar que nos veamos en la necesidad de iniciarle una demanda por falta de pago con embargo de sueldos, bienes, pago de honorarios y costas. Esperando que su buen criterio lo lleve a recuperar su crédito, lo esperamos en calle ______________, localidad _____________, en el horario de _____a _____hs. Y de _____ a ______o bien acérquese a su cobrador.'</cell>
          <cell name="texto1" width="90" top="155" height="5" multiline="true" align="left" maxlines="2">'c'*1000</cell>
        <cell name="texto2" width="90" top="205" height="5" multiline="true" align="justified" maxlines="3">'a'*1000</cell>
        </elements>
      </container>
    </elements>
  </body>
</form>

=== teosoncco/python-print-form/pyForm/PyFormTest.xml
<?xml version="1.0" encoding="iso-8859-1"?>

<form xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="PyForm.xsd" format="legal" orientation="portrait" unit="mm"
  author="Mariano Reingart" subject="Prueba de PyForm" collateCopies="true">
  <margins top="10" left="5"/>
  <variables>
    <variable name="lala" value="'dfasfsdaf'"/>
    <variable name="debug" value="False"/>
  </variables>
  
  <title>titulo</title>
  
  <implementation module="test" function="etiquetas"/>
    
  <body name="hoja1" copies="2">
    <backgroundColor standard="white"/>
    <foregroundColor standard="black"/>
    <defaultFont  family="arial" size="10"/>
    <defaultLineWidth>0.2</defaultLineWidth>
    <elements>
      <container name="etiqueta" top="0" left="0" width="105" height="37" rows="8" cols="2"
        enabled="len(items)&gt;(pgno *16 + row * 2 + col)">
        <elements>
          <rect left="0" top="0" width="105" height="37" lineWidth="0.2" />
          <text top="10" left="10" name="nombre">items[ pgno *16 + row * 2 + col ] </text>
          <text top="15" left="10" name="direccion">'direccion[%s][%s][%s]' % (pgno,row,col) <font
              family="arial" bold="true" />
          </text>
          <cell top="20" left="0" width="10" height="5" align="right" name="cell1" ><border lineWidth="0.4" top="true" left="true" right="true" bottom="true"/>'celda a la derecha'</cell>
          <cell top="25" left="0" width="10" height="5" align="left"  name="cell2">''<border lineWidth="0.4" top="true" left="true" right="true" bottom="true"/></cell>
          <cell top="30" left="0" width="20" height="5" align="centre" name='celda centrada'>1</cell>
        </elements>
      </container>
    </elements>
  </body>
</form>

=== teosoncco/python-print-form/samples/facturaMatrizDePuntos.xml
<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="file:/home/guido/src/fierro/pyForm/PyForm.xsd" unit="mm" format="(132,48)" engine="text">

    <margins top="0" left="0"/>

    <title>"Factura Libreria Tecnica"</title>

    <implementation module="colofon.client.model.printableModel2" function="printSaleBill"/>

    <variables>
        <variable name="debug" value="False"/>
        <variable name="itemsPP" value="15"/>
    </variables>

    <body name="hoja1" copies="1">
        <backgroundColor standard="white"/>
        <foregroundColor standard="black"/>
        <defaultFont family="arial" size="10"/>

        <elements>
            <cell top="2" left="55" width="30" height="1" align="left">"Nro " + doc.number</cell>
            <cell top="6" left="55" width="13" height="1" align="left">"Cordoba 981"</cell>
            <cell top="7" left="55" width="13" height="1" align="left">doc.date</cell>
            <cell top="0" left="30" width="20" height="1" align="center">doc.letter</cell>
            <cell top="1" left="55" width="140" height="10" align="left" enabled="copy==0">"ORIGINAL"</cell>
            <cell top="1" left="55" width="140" height="10" align="left" enabled="copy==1">"DUPLICADO"</cell>
            <cell top="9" left="8" width="50" height="1" align="left">
                <font compressed="true"/>
                doc.client.legalName</cell>
            <cell top="11" left="10" width="50" height="1" align="left">
                <font compressed="true"/>
                doc.client.address.address</cell>
            <cell top="11" left="50" width="50" height="1" align="left">
                <font compressed="true"/>
                doc.client.address.getAddress([ '%(localidad)s' ])</cell>
            <cell top="13" left="24" width="50" height="1" align="left" enabled="not doc.client.typeIva=='Consumidor Final'">
                <font compressed="true"/>
                doc.client.typeIva</cell>
            <cell top="12" left="18" width="50" height="1" align="left">
                <font compressed="true"/>
                doc.client.cuit</cell>
            <cell top="12" left="38" width="30" height="1" align="left" enabled="not doc.client.typeIva=='Consumidor Final'"><font compressed="true"/>"--------------------"</cell>
            <cell top="12" left="120" width="30" height="1" align="left"><font compressed="true"/>doc.dueDate</cell>
            <cell top="12" left="90" width="140" height="1" align="left"><font compressed="true"/>doc.client.clientCode</cell>


            <!-- Items -->
            <container left="0" top="16" cols="1" rows="15" height="1"  enabled="row &lt; len (doc.itemsAndConcepts)">
                <elements>
                    <cell top="1" left="1" width="6" height="1" align="right">
                        <font compressed="true"/>
                        doc.itemsAndConcepts[row].quantity
                    </cell>
                    <cell top="1" left="8" width="20" height="1" align="left">
                        <font compressed="true"/>
                        doc.itemsAndConcepts[row].productCode
                    </cell>
                    <cell top="1" left="29" width="40" height="1" align="left">
                        <font compressed="true"/>
                        doc.itemsAndConcepts[row].description
                    </cell>
                     <cell top="1" left="70" width="25" height="1" align="left">
                        <font compressed="true"/>
                        doc.itemsAndConcepts[row].visibleAuthor
                    </cell>
                    <cell top="1" left="96" width="10" height="1" align="right">
                        <font compressed="true"/>
                        doc.itemsAndConcepts[row].price.format(symbol=False)
                    </cell>
                    <cell top="1" left="107" width="12" height="1" align="centre">
                        <font compressed="true"/>
                    doc.itemsAndConcepts[row].discount.format("%0.2f")</cell>
                    <cell top="1" left="120" width="12" height="1" align="right">
                        <font compressed="true"/>
                        doc.itemsAndConcepts[row].total.format(symbol=False)
                    </cell>
                </elements>
            </container>

            <cell top="36" left="21" width="15" height="1" align="left">
                <font compressed="true"/>
                doc.payments </cell>

            <cell top="36" left="90" width="50" height="1" align="centre">
	                <font compressed="true"/>
           	        "Cant de ejemplates" + str(doc.productQuantity)
	          </cell>

            <cell top="40" left="15" width="60" height="1" align="left" multilines="2">
                <font compressed="true"/>
                doc.footerNotes()
            </cell>


            <cell top="38" left="60" width="20" height="1" align="right">doc.subTotal.format(symbol=False)</cell>

          
            <cell top="40" left="60" width="20" height="1" align="right">
                doc.total.format(symbol=False)
            </cell>
            <cell top="38" left="21" width="50" height="10" align="left">
	    		<font compressed="true"/>
                        "SON: " + doc.total.getSonPesos()
		    </cell>
        </elements>

    </body>
</form>
